### ISSUE TITLE
no search results on Greebo Update

### ISSUE THREAD

**Issue by pgraetz12** [DavidRoyApp/dokuwiki-plugin-partialsearch#1]
the plugin does not work under the new Greebo Update.
dokuwiki delivers empty results and also in the searchbox are no previews (as usually)

if you want me to do some testing etc. let me know.

rgds
Peter

**Comment by DavidRoyApp** [comment]
Thanks, I'm going to fix it and probably need some help for testing. I'll
mail you when done.

Thx
David

**Comment by DavidRoyApp** [comment]
Solved in #2c34366
Anyway this functionality has been included in Greebo version, so this plugin is no more necessary.
Greebo searching allows to select exact match or contains or begins/ends with.
